### ISSUE TITLE
Connection Lost ! Unable to Connect to any of my Devices :(

### ISSUE THREAD

**Issue by Gamezpedia** [myflashlab/bluetooth-ANE#8]
Hi,

i am unable connect to any of my devices to test it :

What i did:
- I tried the demo apk , which never shows me any list on my Xperia Z2 , I press Start Scan and after some time it shows me Scan finished message.
- So i made my own demo app to try it.
- It worked and list down my available paired devices. even it paired one of my device when i tried to connect it via mac.
- But then it just ended on " connectionLost " message every time i tried to connect .
- here are the traces  :

`
Bluetooth is ON ! 
communication >> listen 
dialogStatus >> visibilityTouchYes 
scanMode >> connectableDiscoverable 

Started Scanning.. 
discovering >> discoveringStarted 
Scaning... 

newDiscoverd >> device = HC-05 mac :20:16:06:12:03:18 
newDiscoverd >> device = MYLAPTOP mac :DC:53:60:B9:F9:00 

discovering >> discoveringFinished 
Scan finished. 

Connecting to MAC >>20:16:06:12:03:18
communication >> connecting 
Connecting to the device... 
communication >> listen 
connection >> unableToConnect 
communication >> listen 
communication >> none 
communication >> listen 
connection >> connectionLost 
Connection Lost!!! 

Connecting to MAC >>DC:53:60:B9:F9:00
communication >> connecting 
Connecting to the device... 
communication >> listen 
connection >> unableToConnect 
communication >> listen 
communication >> none 
communication >> listen 
connection >> connectionLost 
Connection Lost!!!
 `
- Kindly let me know if i am doing something wrong or the ane is missing some features to connect to other devices such as my laptop or hc-05 bluetooth module attached to a microcontroller.

thanks

**Comment by myflashlab** [comment]
The Bluetooth ANE is built to connect two Android devices to each other. Not other devices. Maybe in future we would consider supporting that but there are not many requests on that feature and because of that, we don't have any firm plan for that. However, you can contact us directly through http://www.myflashlabs.com/contact/ and possibly ask for a custom order quote.
